# Generated by Django 4.2.7 on 2025-09-13 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Reserva'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('fecha_salida__gt', models.F('fecha_entrada'))), name='fecha_salida_mayor_entrada', violation_error_message='La fecha de salida debe ser posterior a la fecha de entrada.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_personas__gt', 0)), name='cantidad_personas_positiva', violation_error_message='La cantidad de personas debe ser mayor a cero.'),
        ),
    ]
